version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "80"
    depends_on:
      - backend
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.coolsun.rule=Host(`hostel.coolsun.co.uk`)
      - traefik.http.routers.coolsun.entrypoints=web,websecure
      - traefik.http.routers.coolsun.tls=true
      - traefik.http.services.coolsun.loadbalancer.server.port=80

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - hostel_sqlite_data:/app/instance
      - hostel_uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: always

volumes:
  hostel_sqlite_data:
  hostel_uploads:
