version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    expose:
      - "80"
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=80
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    restart: always
